version: 2
updates:
- package-ecosystem: pip
  directory: "/ebr_board"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
  reviewers:
  - eugene-davis
  - bestdeveloperever
  commit-message:
    prefix: fix
    prefix-development: chore
    include: scope
